version: '3.8'

services:
  nginx:
    image: nginx:1.20.0
    container_name: nginx
    volumes:
      - ./tools/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  drp:
    image: drp:latest
    container_name: drp
    build:
      context: .
      dockerfile: ./tools/docker/drp/Dockerfile
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  storybook:
    image: storybook:latest
    container_name: storybook
    build:
      context: .
      dockerfile: ./tools/docker/storybook/Dockerfile
    ports:
      - 8081:8081
