version: '3.4'

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  darkrushphotography:
    image: darkrushphotography
    build:
      context: .
      dockerfile: ./tools/docker/darkrushphotography/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  bestof:
    image: bestof
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  storybookui:
    image: darkrushphotography
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  cypress:
    image: cypress
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
