version: '3.8'

services:
  nginx:
    image: nginx:1.20.0
    container_name: nginx
    volumes:
      - ./tools/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  website:
    image: website:latest
    container_name: website
    build:
      context: .
      dockerfile: ./tools/docker/website/Dockerfile
    env_file:
      - ./tools/docker/website/.env
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  api:
    image: api:latest
    container_name: api
    build:
      context: .
      dockerfile: ./tools/docker/api/Dockerfile
    env_file:
      - ./tools/docker/api/.env
    environment:
      - PORT=8081
    ports:
      - 8081:8081

  socket:
    image: socket:latest
    container_name: socket
    build:
      context: .
      dockerfile: ./tools/docker/web-socket/Dockerfile
    env_file:
      - ./tools/docker/web-socket/.env
    environment:
      - PORT=8082
    ports:
      - 8082:8082
