config:
  deployment:location: East US
  deployment:resourceGroupName: drp-rg
  deployment:cosmosDbDatabaseAccountName: drp-cosmos-db-account
  deployment:cosmosDbDatabaseName: drp-cosmos-db-database
  deployment:cosmosDbContainerName: content
  deployment:uploadFunctionsAppName: drpUploadFunctionsApp
  deployment:publishFunctionsAppName: drpPublishFunctionsApp
  deployment:uploadsStorageAccountName: drpUploadsSa
  deployment:uploadsContainerName: uploads
  deployment:blobStorageAccountName: drpBlobSa
  deployment:homeBlobContainerName: home
  deployment:reviewBlobContainerName: review
  deployment:reviewsBlobContainerName: reviews
  deployment:photoOfTheWeekBlobContainerName: photo-of-the-week
  deployment:storiesBlobContainerName: stories
  deployment:destinationsBlobContainerName: destinations
  deployment:blobStorageCdnProfileName: drpBlobsCdn
  deployment:blobStorageCdnEndpointName: dark-rush-photography
