name: Install Web App (separate as multi-container in preview)
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}
      AZ_RESOURCE_GROUP: drp-grp
      AZ_APP_SERVICE_PLAN: drp-app-service-plan
      AZ_WEB_APP_NAME: dark-rush-photography
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          working-directory: ./tools/ci/
          inlineScript: az webapp create --resource-group ${{ env.AZ_RESOURCE_GROUP }} --plan ${{ env.AZ_APP_SERVICE_PLAN }} --name ${{ env.AZ_WEB_APP_NAME }} --multicontainer-config-type compose --multicontainer-config-file ./docker/docker-compose.yml
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          working-directory: ./tools/ci/
          inlineScript: az webapp identity assign --name ${{ env.AZ_WEB_APP_NAME }} --resource-group ${{ env.AZ_RESOURCE_GROUP }}
