name: Pull Request CI
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure Azure Credentials
        uses: az-actions/configure-az-credentials@v1
        with:
          arm-client-id: ${{ secrets.ARM_CLIENT_ID }}
          arm-client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          arm-tenant-id: ${{ secrets.ARM_TENANT_ID }}
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1
      - run: npm install
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
