name: 'Pull Request'
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          npm install
      - name: Prebuild Website
        run: npm run prebuild:ssr
      - name: Build Website
        run: npm run build:ssr
      - name: Build Api
        run: npx nx run api:build:production
      - name: Build Websocket
        run: npx nx run web-socket:build:production
      - name: Copy files for Docker
        run: npm run dc:copy
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1
      - name: Install Pulumi Dependencies
        run: npm install
        working-directory: ./tools/ci/
      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          work-dir: ./tools/ci/
          command: preview
          stack-name: ci
        env:
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
