name: 'Push Master'
on:
  push:
    branches:
      - master
jobs:
  up:
    name: Up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          npm install
      - name: Storybook Copy Files
        run: npm run dc:copy
      - name: Storybook Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs-build
          TARGET_FOLDER: docs
      - name: Pulumi Install CLI
        uses: pulumi/setup-pulumi@v2
      - name: Pulumi Install Dependencies
        run: npm install
        working-directory: ./tools/ci/
      - name: Pulumi Up
        uses: pulumi/actions@v3
        with:
          work-dir: ./tools/ci/
          command: up
          stack-name: ci
        env:
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
